
CREATE TABLE IF NOT EXISTS USUARIO
(
    CPF_USUARIO CHAR(11) PRIMARY KEY,
    NOME_USUARIO TEXT,
    EMAIL_USUARIO TEXT,
    SENHA_USUARIO TEXT,
    CAMINHO_IMAGEM_PERFIL TEXT
);

GO

CREATE TABLE IF NOT EXISTS PASSEIO
(
    CODIGO_PASSEIO INTEGER PRIMARY KEY autoincrement,
    HORARIO_PASSEIO TEXT,
    HORARIO_CONCLUSAO_PASSEIO TEXT,
    ORIGEM_PASSEIO TEXT,
    DESTINO_PASSEIO TEXT,
    CAMINHO_IMAGEM TEXT
);

GO

CREATE TABLE IF NOT EXISTS PET
(
    CODIGO_PET INTEGER PRIMARY KEY autoincrement,
    NOME_PET TEXT,
    ESPECIE_PET TEXT,
    GENERO_PET TEXT,
    CPF_USUARIO TEXT,
    CAMINHO_IMAGEM TEXT

);

GO

CREATE TABLE IF NOT EXISTS PET_PASSEIO
(
    CODIGO_PET_PASSEIO INTEGER PRIMARY KEY autoincrement,
    CODIGO_PET INT,
    CODIGO_PASSEIO INT
);

GO

